views/menus/views.py
from flask import Flask, render_template, redirect, url_for, request, abort,session, Response, Blueprint
from flask_login import LoginManager, login_user, logout_user, login_required,current_user
from werkzeug.utils import secure_filename
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import engine
from sqlalchemy.sql import func, text
import os
import requests, json
    # CORREOS
import smtplib
from flask_mail import Message, Mail
    # FORMULARIOS
from forms.forms import *

mail = Mail()
app = Flask(__name__)
db = SQLAlchemy(app)
mail.init_app(app)

menus = Blueprint('menus', __name__, template_folder='templates', static_folder='static')

@menus.route('/')
def menu_inicio():
    return render_template("Inicio/inicio.html")

@menus.route('/acerca_de_nosotros', methods=['GET', 'POST'])
def menu_inicio_nosotros():
    from models.models import db
    resultados = db.engine.execute(text("SELECT * FROM preguntas_frecuentes"))
    return render_template("Nosotros/inicio.html", resultados=resultados)

@menus.route('/contactanos', methods=['GET', 'POST'])
def menu_inicio_contactanos():
    form = ContactForm()
    if request.method == 'POST':
        Nombre = form.nombre.data
        Correo = form.correo.data
        Mensaje = form.mensaje.data
        #ENVIO DE CORREO A NOTIFICACIONES
        msg = Message(Nombre, sender='contacto@vtesta.info', recipients=['ivannaje15@gmail.com'])
        msg.html = """
              <h2>
              El Cliente: %s <br>
              Con el Correo: %s <br>
              Nos manda el Mensaje: %s <br>
              </h2>
              """ % (Nombre, Correo, Mensaje)
        try:
             mail.send(msg)
        except Exception as e:
            # Print any error messages to stdout
            #print(e)
            print('Se envio')
        return redirect(url_for('menus.menu_inicio_contactanos_envio'))
    return render_template("Contacto/inicio.html", form=form)

@menus.route('/contactanos/envio_exitoso')
def menu_inicio_contactanos_envio():
    return render_template("Contacto/respuesta.html")

@menus.route('/centro_de_ayuda', methods=['GET', 'POST'])
def menu_inicio_centro_de_ayuda():
    form = ContactForm()
    return render_template("Centro_ayuda/inicio.html", form=form)

@menus.route('/desarrollo_personalizado', methods=['GET', 'POST'])
def menu_inicio_desarrollo_personalizado():
    form = ContactForm()    
    return render_template("Desarrollo/inicio.html", form=form)

@menus.route('/terminos_y_condiciones')
def menu_inicio_terminos_y_condiciones():
    from models.models import db
    resultados = db.engine.execute(text("SELECT * FROM terminos_y_condiciones"))
    return render_template("Terminos/inicio.html", resultados=resultados)

@menus.route('/politica_de_privacidad')
def menu_inicio_politica_de_privacidad():
    from models.models import db
    resultados = db.engine.execute(text("SELECT * FROM politica_de_privacidad"))
    return render_template("Condiciones/inicio.html", resultados=resultados)

views/menus/templates/Centro_ayuda/inicio.html
{% extends "mainpages/page-layout.html" %}
{% block Titulo %}Vtesta | Centro de Ayuda{% endblock %}
{% block contenido %}
<header>
  <div class="page-header min-vh-50" style="background-image: url(&quot;https://demos.creative-tim.com/soft-ui-design-system-pro/assets/img/curved-images/curved10.jpg&quot;); background-position-y: 50%;">
    <span class="mask bg-gradient-dark"></span>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-white text-center">
          <h2 class="text-white">Necesitas Ayuda?</h2>
          <p class="lead">Aqui podras encontrar mas informacion sobre nuestros productos y servicios.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="position-relative overflow-hidden" style="height:36px;margin-top:-35px;">
    <div class="w-full absolute bottom-0 start-0 end-0" style="transform: scale(2);transform-origin: top center;color: #f8f9fa;">
      <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
      </svg>
    </div>
  </div>
  <!-- <div class="container">
    <div class="row bg-white shadow mt-n6 border-radius-md py-4 p-3 position-relative">
      <div class="col-md-10 mb-md-0 mb-2">
        <div class="input-group">
          <span class="input-group-text"><i class="fas fa-search" aria-hidden="true"></i></span>
          <input type="text" class="form-control" placeholder="Search for your answer">
        </div>
      </div>
      <div class="col-md-2 ps-md-0">
        <button type="button" class="btn bg-gradient-primary w-100 mb-0 h-100 position-relative z-index-2">Search</button>
      </div>
    </div>
  </div> -->
</header>

<section class="py-lg-5">
  <div class="container">
    <div class="row mt-lg-5 mt-4">
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-slack.svg') }}" alt="logo">
            <h5 class="mt-2">Slack bot</h5>
            <p class="mb-3">If everything I did failed - which it doesn't, it actually succeeds - just the fact that I'm willing to fail is an inspiration. People are so scared to lose that they don't even try. And this is sad.</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-info icon-move-right">
              Check more
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card mb-3">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-spotify.svg') }}" alt="logo">
            <h5 class="mt-2">Looking great</h5>
            <p class="mb-3">You have the opportunity to play this game of life you need to appreciate every moment. A lot of people don’t appreciate the moment until it’s motivating the doers.</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-success icon-move-right">
              See details
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card mb-3">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-asana.svg') }}" alt="logo">
            <h5 class="mt-2">Developer First</h5>
            <p class="mb-3">For standing out. But the time is now to be okay to be the greatest you. Would you believe in what you believe in, if you were the only one who believed it? What do you think?</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-warning icon-move-right">
              View journey
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card mb-3">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-invision.svg') }}" alt="logo">
            <h5 class="mt-2">Prepare launch</h5>
            <p class="mb-3">Society has put up so many boundaries, so many limitations on what’s right and wrong that it’s almost impossible to get a pure thought out. It’s like a little kid, a little boy.</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-dark icon-move-right">
              Check out more
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card mb-3">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-jira.svg') }}" alt="logo">
            <h5 class="mt-2">Premium support</h5>
            <p class="mb-3">Pink is obviously a better color. Everyone’s born confident, and everything’s taken away from you matters is the people who are sparked by it follow their dreams, too.</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-info icon-move-right">
              See all
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card mb-3">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-weave.svg') }}" alt="logo">
            <h5 class="mt-2">Design tools</h5>
            <p class="mb-3">Constantly growing. We’re constantly making mistakes. We’re constantly trying to express ourselves, find the meaning and actualize our dreams the position that we want to be.</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-danger icon-move-right">
              Find story
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card mb-3">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-invision.svg') }}" alt="logo">
            <h5 class="mt-2">Prepare launch</h5>
            <p class="mb-3">Society has put up so many boundaries, so many limitations on what’s right and wrong that it’s almost impossible to get a pure thought out. It’s like a little kid, a little boy.</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-dark icon-move-right">
              Check out more
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card mb-3">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-jira.svg') }}" alt="logo">
            <h5 class="mt-2">Premium support</h5>
            <p class="mb-3">Pink is obviously a better color. Everyone’s born confident, and everything’s taken away from you matters is the people who are sparked by it follow their dreams, too.</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-info icon-move-right">
              See all
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5">
        <div class="card mb-3">
          <div class="card-body border-radius-lg position-relative overflow-hidden pb-4 px-sm-5 ">
            <img class="w-25 mb-3" src="{{ url_for('static', filename='img/logos/small-logos/logo-weave.svg') }}" alt="logo">
            <h5 class="mt-2">Design tools</h5>
            <p class="mb-3">Constantly growing. We’re constantly making mistakes. We’re constantly trying to express ourselves, find the meaning and actualize our dreams the position that we want to be.</p>
            <a href="javascript:;" class="font-weight-bold text-xs text-uppercase font-weight-bolder text-danger icon-move-right">
              Find story
              <i class="fas fa-arrow-right text-xs ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="py-5">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-8 mx-auto text-center">
        <div class="ms-3 mb-md-5">
          <h2>Si no encuentras la respuesta</h2>
          <p class="lead">Puedes contactarnos para obtener ayuda de nuestros productos / servicios.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="card card-plain">
          <form id="contact-form" method="post" autocomplete="off" action="{{url_for('menus.menu_inicio_contactanos')}}">
            {{form.csrf_token}}
                <div class="card-body pb-2">
                  <div class="row">
                    <div class="col-md-6">
                      <label>Nombre Completo</label>
                      <div class="input-group mb-4">
                        {{form.nombre(class="form-control", placeholder="Nombre Apellido Completo")}}
                      </div>
                    </div>
                    <div class="col-md-6 ps-md-2">
                      <label>Correo Electronico</label>
                      <div class="input-group">
                        {{form.correo(class="form-control", placeholder="ejemplo@ejemplo.com")}}
                      </div>
                    </div>
                  </div>
                  <div class="form-group mb-0 mt-md-0 mt-4">
                    <label>En que podemos ayudarte?</label>
                    {{form.mensaje(class="form-control", placeholder="Describe tu proyecto o duda aqui.")}}
                  </div>
                  <div class="g-recaptcha" data-sitekey="{{sitekey}}" data-callback="correctCaptcha" align = "center" ></div>
                  <div class="row">
                    <div class="col-md-12 text-center">
                      {{ form.enviar(class="btn bg-gradient-vtesta mt-3 mb-0 text-white", value="Enviar Mensaje")}}
                    </div>
                  </div>
                </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

views/menus/templates/Condiciones/inicio.html
{% extends "mainpages/page-layout.html" %}
{% block Titulo %}Vtesta | Política de privacidad{% endblock %}
{% block contenido %}
  <section class="pt-3 pt-md-5 pb-md-5 pt-lg-7">
    <div class="container">
      <div class="col-lg-12 col-md-10 mx-auto pb-5">
        <div class="card shadow-lg">
          <div class="card-header bg-gradient-vtesta p-5 position-relative">
            <h3 class="text-white mb-0">Política &amp; Privacidad</h3>
            <p class="text-white opacity-8 mb-4">Ultima Modificacion: Mar 14 2022</p>
            <div class="position-absolute w-100 z-index-1 bottom-0 ms-n5">
              <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto" style="height:7vh;min-height:50px;">
                <defs>
                  <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
                </defs>
                <g class="moving-waves">
                  <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"></use>
                  <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"></use>
                  <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"></use>
                  <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"></use>
                  <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"></use>
                  <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"></use>
                </g>
              </svg>
            </div>
          </div>
          <div class="card-body p-5 pt-0">
            <p>
              {% for datos in resultados %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 1 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 1 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 2 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 2 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 3 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 3 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 4 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 4 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 5 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 5 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 6 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 6 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 7 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 7 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 8 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 8 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
                {% if datos.tipo == 'titulo' and datos.secuencia == 9 and datos.visible == 1 %}
                  <h3>{{datos.texto}}</h3>
                {% endif %}
                {% if datos.tipo == 'contenido' and datos.secuencia == 9 and datos.visible == 1 %}
                  <ul align="justify">
                    <li>{{datos.texto}}</li>
                  </ul>
                {% endif %}
              {% endfor %}
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

views/menus/templates/Contacto/inicio.html
{% extends "mainpages/page-layout.html" %}
{% block Titulo %}Vtesta | Contacto{% endblock %}
{% block contenido %}
  <header>
    <div class="page-header min-vh-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" 
        src="{{url_for('static', filename='img/curved-images/curved8.jpg')}}" alt="image">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-vtesta">Contactanos</h3>
                <p class="mb-0">
                  Nuestros expertos están disponibles para ti las 24 horas del día, los 7 días de la semana.
                </p>
              </div>
              <form method="post" autocomplete="off" action="{{url_for('menus.menu_inicio_contactanos')}}">
                {{form.csrf_token}}
                <div class="card-body pb-2">
                  <div class="row">
                    <div class="col-md-6">
                      <label>Nombre Completo</label>
                      <div class="input-group mb-4">
                        {{form.nombre(class="form-control", placeholder="Nombre Apellido Completo")}}
                      </div>
                    </div>
                    <div class="col-md-6 ps-md-2">
                      <label>Correo Electronico</label>
                      <div class="input-group">
                        {{form.correo(class="form-control", placeholder="ejemplo@ejemplo.com")}}
                      </div>
                    </div>
                  </div>
                  <div class="form-group mb-0 mt-md-0 mt-4">
                    <label>En que podemos ayudarte?</label>
                    {{form.mensaje(class="form-control", placeholder="Describe tu proyecto o duda aqui.")}}
                  </div>
                  <div class="g-recaptcha" data-sitekey="{{sitekey}}" data-callback="correctCaptcha" align = "center" ></div>
                  <div class="row">
                    <div class="col-md-12 text-center">
                      {{ form.enviar(class="btn bg-gradient-vtesta mt-3 mb-0 text-white", value="Enviar Mensaje")}}
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

views/menus/templates/Contacto/respuesta.html
{% extends "mainpages/page-layout.html" %}
{% block Titulo %}Vtesta | Contacto{% endblock %}
{% block contenido %}
  <header>
    <br><br><br>
    <section class="my-10 py-5 bg-gradient-dark position-relative" style="background-image:url({{ url_for('static', filename='img/nastuh.jpg') }})">
      <span class="mask bg-gradient-dark opacity-8"></span>
      <div class="container position-relative z-index-2">
        <div class="row">
          <div class="col-lg-6 mx-auto text-center">
            <h3 style="color: white;">Envio Exitoso</h3>
          </div>
        </div>
        <br><br>
        <div class="row">
          <div class="col-lg-5 col-md-8 m-auto text-start">
            <h5 class="text-white mb-lg-0 mb-5"  align="center">
              Gracias por contactarnos, en unos minutos un asesor se pondra en contacto contigo.
            </h5>
          </div>
          <div class="col-lg-6 m-auto">
            <div class="row">
              <div class="col-sm-4 col-6 ps-sm-0 ms-auto">
                <a href="{{url_for('menus.menu_inicio')}}">
                  <button type="button" class="btn bg-gradient-warning mb-0 ms-lg-3 ms-sm-2 mb-sm-0 mb-2 me-auto w-100 d-block">Inicio</button>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </header>
{% endblock %}

views/menus/templates/Terminos/inicio.html
{% extends "mainpages/page-layout.html" %}
{% block Titulo %}Vtesta | T&C{% endblock %}
{% block contenido %}
  <section class="pt-3 pt-md-5 pb-md-5 pt-lg-7">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="card shadow-lg mb-5">
            <div class="card-header bg-gradient-vtesta p-5 position-relative">
              <h3 class="text-white mb-0">Terminos &amp; Condiciones</h3>
              <p class="text-white opacity-8 mb-4">Ultima Modificacion: Mar 14 2022</p>
              <div class="position-absolute w-100 z-index-1 bottom-0 ms-n5">
                <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto" style="height:7vh;min-height:50px;">
                  <defs>
                    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
                  </defs>
                  <g class="moving-waves">
                    <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"></use>
                    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"></use>
                    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"></use>
                    <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"></use>
                    <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"></use>
                    <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"></use>
                  </g>
                </svg>
              </div>
            </div>
            <div class="card-body p-5">
              <p>
                {% for datos in resultados %}
                  {% if datos.tipo == 'titulo' and datos.secuencia == 1 and datos.visible == 1 %}
                    <h3>{{datos.texto}}</h3>
                  {% endif %}
                  {% if datos.tipo == 'contenido' and datos.secuencia == 1 and datos.visible == 1 %}
                    <ul align="justify">
                      <li>{{datos.texto}}</li>
                    </ul>
                  {% endif %}
                  {% if datos.tipo == 'titulo' and datos.secuencia == 2 and datos.visible == 1 %}
                    <h3>{{datos.texto}}</h3>
                  {% endif %}
                  {% if datos.tipo == 'contenido' and datos.secuencia == 2 and datos.visible == 1 %}
                    <ul align="justify">
                      <li>{{datos.texto}}</li>
                    </ul>
                  {% endif %}
                  {% if datos.tipo == 'titulo' and datos.secuencia == 3 and datos.visible == 1 %}
                    <h3>{{datos.texto}}</h3>
                  {% endif %}
                  {% if datos.tipo == 'contenido' and datos.secuencia == 3 and datos.visible == 1 %}
                    <ul align="justify">
                      <li>{{datos.texto}}</li>
                    </ul>
                  {% endif %}
                  {% if datos.tipo == 'titulo' and datos.secuencia == 4 and datos.visible == 1 %}
                    <h3>{{datos.texto}}</h3>
                  {% endif %}
                  {% if datos.tipo == 'contenido' and datos.secuencia == 4 and datos.visible == 1 %}
                    <ul align="justify">
                      <li>{{datos.texto}}</li>
                    </ul>
                  {% endif %}
                {% endfor %}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}